version: '3.8'

services:
  mongodb:
    image: mongo:6.0.12
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - lms-network

  backend:
    image: yourusername/lms-backend:latest
    container_name: lms-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/lms?authSource=admin
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,your-domain.com
    networks:
      - lms-network

  frontend:
    image: yourusername/lms-frontend:latest
    container_name: lms-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongodb_data: